In [203]:
import numpy as np
import pandas as pd

In [204]:
df = pd.read_csv('50_Startups.csv')
df.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [205]:
df['R&D Spend'].mean() / 10000
df.shape

(50, 5)

In [206]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration',	'Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [207]:
# Select all the input features except the last one
df = df.iloc[:, 0:-1]
df

R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [208]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1, -1] = np.nan

C:\Users\user\AppData\Local\Temp\ipykernel_15216\4139785618.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
C:\Users\user\AppData\Local\Temp\ipykernel_15216\4139785618.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
C:\Users\user\AppData\Local\Temp\ipykernel_15216\4139785618.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1, -1] = np.nan


In [209]:
df.head()


R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [210]:
# Step 1: Impute  all missing values with mean of respective columns

df0 = pd.DataFrame()
df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Adminstration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

# 0th Iteration
df0

R&D Spend  Adminstration  Marketing Spend
21       8.00          15.00            30.00
37       9.25           5.00            20.00
2       15.00          10.00            41.00
14      12.00          11.25            26.00
44       2.00          15.00            29.25

In [211]:
df1 = df0.copy()
df1.iloc[1,0] = np.nan
df1

R&D Spend  Adminstration  Marketing Spend
21        8.0          15.00            30.00
37        NaN           5.00            20.00
2        15.0          10.00            41.00
14       12.0          11.25            26.00
44        2.0          15.00            29.25

In [212]:
# Use first 3 rows to build a model and use the last row for prediction
X = df1.iloc[[0,2,3,4], 1:3]
X

Adminstration  Marketing Spend
21          15.00            30.00
2           10.00            41.00
14          11.25            26.00
44          15.00            29.25

In [213]:
y = df1.iloc[[0,2,3,4], 0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [214]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X, y)
lr.predict(df1.iloc[1,1:].values.reshape(1, 2))


c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.14158651])

In [215]:
df1

R&D Spend  Adminstration  Marketing Spend
21        8.0          15.00            30.00
37        NaN           5.00            20.00
2        15.0          10.00            41.00
14       12.0          11.25            26.00
44        2.0          15.00            29.25

In [216]:
df1.iloc[1, 0] = 23.14

In [217]:
# Remove the col2 imputed value
df1.iloc[3, 1] = np.nan
df1

R&D Spend  Adminstration  Marketing Spend
21       8.00           15.0            30.00
37      23.14            5.0            20.00
2       15.00           10.0            41.00
14      12.00            NaN            26.00
44       2.00           15.0            29.25

In [218]:
X = df1.iloc[[0,1,2,4], [0, 2]]
X

R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [219]:
y = df1.iloc[[0,1,2,4], 1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Adminstration, dtype: float64

In [220]:
lr = LinearRegression()
lr.fit(X, y)
lr.predict(df1.iloc[4, 0:2].values.reshape(1, 2))

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15.4217271])

In [221]:
df1.iloc[3, 1] = 15.42

In [222]:
df1

R&D Spend  Adminstration  Marketing Spend
21       8.00          15.00            30.00
37      23.14           5.00            20.00
2       15.00          10.00            41.00
14      12.00          15.42            26.00
44       2.00          15.00            29.25

In [223]:
# Remove the col3 imputed value
df1.iloc[4, 2] = np.nan
df1

R&D Spend  Adminstration  Marketing Spend
21       8.00          15.00             30.0
37      23.14           5.00             20.0
2       15.00          10.00             41.0
14      12.00          15.42             26.0
44       2.00          15.00              NaN

In [224]:
X = df1.iloc[[0,1,2,3], [0,1]]
X

R&D Spend  Adminstration
21       8.00          15.00
37      23.14           5.00
2       15.00          10.00
14      12.00          15.42

In [225]:
y = df1.iloc[0:4, -1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [226]:
lr = LinearRegression()

lr.fit(X, y)

lr.predict(df1.iloc[4, 0:2].values.reshape(1, 2))

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([50.73738657])

In [227]:
df1.iloc[4, -1] = 50.73

In [228]:
df1

R&D Spend  Adminstration  Marketing Spend
21       8.00          15.00            30.00
37      23.14           5.00            20.00
2       15.00          10.00            41.00
14      12.00          15.42            26.00
44       2.00          15.00            50.73

In [190]:
df0

R&D Spend  Adminstration  Marketing Spend
21       8.00          15.00            30.00
37       9.25           5.00            20.00
2       15.00          10.00            41.00
14      12.00          11.25            26.00
44       2.00          15.00            29.25

In [229]:
df1 - df0

R&D Spend  Adminstration  Marketing Spend
21       0.00           0.00             0.00
37      13.89           0.00             0.00
2        0.00           0.00             0.00
14       0.00           4.17             0.00
44       0.00           0.00            21.48

In [230]:
df1

R&D Spend  Adminstration  Marketing Spend
21       8.00          15.00            30.00
37      23.14           5.00            20.00
2       15.00          10.00            41.00
14      12.00          15.42            26.00
44       2.00          15.00            50.73

In [231]:
df2 = df1.copy()
 
df2.iloc[1, 0] = np.nan
df2

R&D Spend  Adminstration  Marketing Spend
21        8.0          15.00            30.00
37        NaN           5.00            20.00
2        15.0          10.00            41.00
14       12.0          15.42            26.00
44        2.0          15.00            50.73

In [234]:
X = df2.iloc[[0,2,3,4], 1:3]
X

Adminstration  Marketing Spend
21          15.00            30.00
2           10.00            41.00
14          15.42            26.00
44          15.00            50.73

In [235]:
y = df2.iloc[[0,2,3,4], 0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [236]:
lr = LinearRegression()
lr.fit(X, y)
lr.predict(df2.iloc[1, 1:].values.reshape(1, 2))

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([32.32291134])

In [238]:
df2.iloc[1, 0] = 32.32
df2

R&D Spend  Adminstration  Marketing Spend
21       8.00          15.00            30.00
37      32.32           5.00            20.00
2       15.00          10.00            41.00
14      12.00          15.42            26.00
44       2.00          15.00            50.73

In [239]:
df2.iloc[3, 1] = np.nan
X = df2.iloc[[0,1,2,4], [0,2]]
y = df2.iloc[[0,1,2,4], 1]

lr = LinearRegression()
lr.fit(X, y)
lr.predict(df2.iloc[3,[0, 2]].values.reshape(1, 2))

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.70920684])

In [240]:
df2.iloc[3, 1] = 13.70

In [241]:
df2

R&D Spend  Adminstration  Marketing Spend
21       8.00           15.0            30.00
37      32.32            5.0            20.00
2       15.00           10.0            41.00
14      12.00           13.7            26.00
44       2.00           15.0            50.73

In [252]:
df2.iloc[4, 2] = np.nan

X = df2.iloc[0:4, [0,1]]
y = df2.iloc[0:4, -1]

lr = LinearRegression()
lr.fit(X, y)
lr.predict(df2.iloc[4, 0:2].values.reshape(1, 2))

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([48.60026241])

In [255]:
df2.iloc[4, 2] = 48.60
df2

R&D Spend  Adminstration  Marketing Spend
21       8.00           15.0             30.0
37      32.32            5.0             20.0
2       15.00           10.0             41.0
14      12.00           13.7             26.0
44       2.00           15.0             48.6

In [256]:
df2 - df1

R&D Spend  Adminstration  Marketing Spend
21       0.00           0.00             0.00
37       9.18           0.00             0.00
2        0.00           0.00             0.00
14       0.00          -1.72             0.00
44       0.00           0.00            -2.13

In [264]:
df3 = df2.copy()



In [271]:
df3.iloc[1, 0] = np.nan

X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4], 0]

lr = LinearRegression()
lr.fit(X, y)
lr.predict(df3.iloc[1, 1:].values.reshape(1,2))

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([32.29616519])

In [272]:
df3.iloc[1, 0] = 32.29

In [274]:
df3.iloc[3, 1] = np.nan
df3

R&D Spend  Adminstration  Marketing Spend
21       8.00           15.0             30.0
37      32.29            5.0             20.0
2       15.00           10.0             41.0
14      12.00            NaN             26.0
44       2.00           15.0             48.6

In [278]:
X = df3.iloc[[0,1,2,4], [0, 2]]
y = df3.iloc[[0, 1, 2, 4], 1]

lr = LinearRegression()
lr.fit(X, y)
lr.predict(df3.iloc[3, [0,2]].values.reshape(1, 2))

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.71204706])

In [280]:
df3.iloc[3, 1] = 13.7
df3

R&D Spend  Adminstration  Marketing Spend
21       8.00           15.0             30.0
37      32.29            5.0             20.0
2       15.00           10.0             41.0
14      12.00           13.7             26.0
44       2.00           15.0             48.6

In [284]:
df3.iloc[4, 2] = np.nan

X = df3.iloc[0:4, [0, 1]]
y = df3.iloc[0:4, -1]

lr = LinearRegression()
lr.fit(X, y)
lr.predict(df3.iloc[4, 0:2].values.reshape(1, 2))


c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([48.65553435])

In [285]:
df3.iloc[4,2] = 48.60

In [286]:
df3 - df2 

R&D Spend  Adminstration  Marketing Spend
21       0.00            0.0              0.0
37      -0.03            0.0              0.0
2        0.00            0.0              0.0
14       0.00            0.0              0.0
44       0.00            0.0              0.0

In [293]:
df4 = df3.copy()

In [294]:
df4.iloc[1, 0] = np.nan

X = df4.iloc[[0, 2, 3, 4], 1:3]
y = df4.iloc[[0, 2, 3, 4], 0]

lr = LinearRegression()
lr.fit(X, y)
lr.predict(df4.iloc[1, 1:].values.reshape(1, 2))

df4.iloc[1, 0] = 32.29

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [299]:
df4.iloc[3, 1] = np.nan

X = df4.iloc[[0, 1, 2, 4], [0, 2]]
y = df4.iloc[[0,1,2,4], 1]

lr = LinearRegression()
lr.fit(X, y)
lr.predict(df4.iloc[3, [0, 2]].values.reshape(1, 2))

df4.iloc[3, 1] = 13.7

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [304]:
df4.iloc[4, 2] = np.nan

X = df4.iloc[0:4, [0,1]]
y = df4.iloc[0:4, -1]

lr = LinearRegression()
lr.fit(X, y)
lr.predict(df4.iloc[4, 0:2].values.reshape(1,2))

df4.iloc[4, 2] = 48.60

c:\Users\user\anaconda3\envs\missingValues\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [305]:
df4 - df3

R&D Spend  Adminstration  Marketing Spend
21        0.0            0.0              0.0
37        0.0            0.0              0.0
2         0.0            0.0              0.0
14        0.0            0.0              0.0
44        0.0            0.0              0.0